[project]
name = "cbnp"
version = "3.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pyinstaller>=6.13.0",
    "requests>=2.32.4",
    "rumps>=0.4.0",
    "websockets>=15.0.1",
]
